name: luxai_s2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - scipy
  - pip
  - cython
  - tqdm
  - yaml
  - termcolor
  - pyyaml
  - notebook
  - tensorboard
  - dm-tree
  - seaborn
  - gymnasium

