name: Algorithm Badge Updater

on:
  push:
    branches:
      - '!main'
      - 'v0.0.3-Hybrid'
      - '!v0.0.3-TDK'
      - '!v0.0.3-Monolithic'
      - '!v0.0.3-SUT'
      - '!v0.0.2-MA-Eval'
      - '!v0.0.1-action-per-unit'
      - '!v0.0.1-factory-net'
    paths:
      - README.md
      - .github/workflows/badge.yml
jobs:
  build:
    name: Badge Updater
    runs-on: ubuntu-latest
    steps:
      - name: Update Algorithm Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 5a256487d767cc5d606d29bd521a18ae
          filename: algo.json
          label: algorithm
          message: M-PPO
          color: orange

      - name: Update TDK Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
            auth: ${{ secrets.GIST_SECRET }}
            gistID: 59b429b8fd9c4a525959c66dfa4ab97e
            filename: TDK.json
            label: TDK
            message: Passed
            color: green

      - name: Update Status Badge
        uses: schneegans/dynamic-badges-action@v1.6.0
        with:
              auth: ${{ secrets.GIST_SECRET }}
              gistID: 68de4e5ec35fcfe2a3f5583059a90521
              filename: status.json
              label: Status
              message: Active
              color: green