name: Pylint

on:
  push:
    branches:
      - 'v0.0.1-CNN-mixed'
      - '!master'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install devtools
      run: |
        sudo apt update -y && apt upgrade -y && apt install -y build-essential && apt-get install -y manpages-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r envs/pip/requirements.txt
        pip install --no-cache-dir vec_noise --upgrade luxai_s2
        pip install --no-cache-dir --upgrade "jax[cuda11_cudnn82]==0.4.7" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
        pip install --no-cache-dir git+https://github.com/RoboEden/jux.git@dev
        pip install --no-cache-dir pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py' ':!:src/luxai_s2/*' ':!:src/sb3_contrib/*' ':!:src/stable_baselines3/*') --fail-under=5
