name: Pylint

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install devtools
      run: |
        sudo apt-get update -y 
        sudo apt-get upgrade -y 
        sudo apt-get install -y build-essential 
        sudo apt-get install -y manpages-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r envs/pip/requirements.txt
        pip install pettingzoo==1.24.1
        pip install vec-noise==1.1.4
        pip install stable_baselines3
        pip install sb3-contrib
        pip install --upgrade luxai_s2
        pip install --upgrade "jax[cuda11_cudnn82]==0.4.7" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
        pip install git+https://github.com/RoboEden/jux.git@dev
        pip install pylint

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py' ':!:src/luxai_s2/*' ':!:src/sb3_contrib/*' ':!:src/stable_baselines3/*') --fail-under=5
