name: PyTest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install devtools
      run: |
        sudo apt-get update -y 
        sudo apt-get upgrade -y 
        sudo apt-get install -y build-essential 
        sudo apt-get install -y manpages-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r envs/pip/requirements.txt
        pip install pytest
        pip install vec-noise==1.1.4
        pip install stable_baselines3==1.7.0
        pip install gym==0.21
        pip install --upgrade luxai_s2
        pip install sb3-contrib
    - name: Run PyTest
      run: |
        PYTHONPATH=src/. pytest
